### PR TITLE
Reduced number of steps

### PR DESCRIPTION
**Pull request by revolter**
Added automatic cursor positioning inside the comment.

### CODE REVIEW

**Comment by flexih** [comment]
Hi revolter, thanks for your work :)

**Comment by revolter** [comment]
Hi, my pleasure :smile:

**Comment by flexih** [comment]
Hi, I create a new branch "setting", solve the bug, deleting leading/trailing space.

**Comment by revolter** [comment]
@flexih, I don't understand

**Comment by flexih** [comment]
Hi, I create a new branch called setting. It use some of your code, and remove leading/trailing space left by uncomment action. And now it merged to branch master.

**Comment by revolter** [comment]
I understand now, please see https://github.com/flexih/Xcode-CComment/pull/5.

**Pull request merged**
